services:
  apache:
    build: .
    ports:
      - 80:80
    links:
      - mysql
      - es
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento1234
  es:
    image: elasticsearch:7.17.5
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  redis:
    image: redis
    ports:
      - 6379:6379
  varnish:
    image: varnish:stable
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
    ports:
      - 8080:80